export const seedData = {
  stats: {
    students: 3,
    openComplaints: 2,
    pendingLeaves: 1,
    notices: 3,
  },
  students: [
    {
      id: 1,
      full_name: "Satyam Mall",
      email: "satyam@hostelhub.com",
      phone: "9876543210",
      block: "Block B",
      room_number: "529",
      course: "B.Tech CSE",
      year_level: "2nd Year",
      guardian_name: "Rakesh Mall",
      guardian_phone: "9876501234",
      created_at: "2026-07-09 10:50:00",
    },
    {
      id: 2,
      full_name: "Aarav Singh",
      email: "aarav@hostelhub.com",
      phone: "9876500001",
      block: "Block A",
      room_number: "214",
      course: "BBA",
      year_level: "2nd Year",
      guardian_name: "Meena Singh",
      guardian_phone: "9876502222",
      created_at: "2026-07-09 10:50:00",
    },
    {
      id: 3,
      full_name: "Rakshit Thareja",
      email: "jaythareja123@gmail.com",
      phone: "9876503333",
      block: "Block B",
      room_number: "531",
      course: "B.Tech CSE",
      year_level: "2nd Year",
      guardian_name: "Rajesh Thareja",
      guardian_phone: "9876504444",
      created_at: "2026-07-09 10:50:00",
    },
  ],
  complaints: [
    {
      id: 1,
      student_id: 1,
      title: "Water leakage in bathroom",
      description: "Continuous seepage near the shower area.",
      category: "Maintenance",
      priority: "High",
      status: "In Progress",
      created_at: "2026-07-09 10:50:00",
      full_name: "Satyam Mall",
    },
    {
      id: 2,
      student_id: 1,
      title: "Wi-Fi disconnecting often",
      description: "Internet drops every evening in the room.",
      category: "Technical",
      priority: "Medium",
      status: "Open",
      created_at: "2026-07-09 10:50:00",
      full_name: "Satyam Mall",
    },
    {
      id: 3,
      student_id: 2,
      title: "Broken study lamp",
      description: "Hostel study lamp is not working.",
      category: "Electrical",
      priority: "Low",
      status: "Resolved",
      created_at: "2026-07-09 10:50:00",
      full_name: "Aarav Singh",
    },
  ],
  leaveApplications: [
    {
      id: 1,
      student_id: 1,
      reason: "Family function",
      start_date: "2026-07-14",
      end_date: "2026-07-17",
      status: "Pending",
      approver_note: "",
      created_at: "2026-07-09 10:50:00",
      full_name: "Satyam Mall",
    },
    {
      id: 2,
      student_id: 1,
      reason: "Medical consultation",
      start_date: "2026-06-28",
      end_date: "2026-06-29",
      status: "Approved",
      approver_note: "Approved by warden.",
      created_at: "2026-07-09 10:50:00",
      full_name: "Satyam Mall",
    },
    {
      id: 3,
      student_id: 2,
      reason: "Home visit",
      start_date: "2026-07-20",
      end_date: "2026-07-22",
      status: "Rejected",
      approver_note: "Exam schedule clashes with leave dates.",
      created_at: "2026-07-09 10:50:00",
      full_name: "Aarav Singh",
    },
  ],
  notices: [
    {
      id: 1,
      title: "Semester entry timings updated",
      content: "Entry gate closes at 9:30 PM on weekdays and 10:30 PM on weekends.",
      category: "Rules",
      is_important: 1,
      created_at: "2026-07-09 10:50:00",
    },
    {
      id: 2,
      title: "Water tank cleaning",
      content: "Water supply will be paused from 11 AM to 2 PM on Saturday for maintenance.",
      category: "Maintenance",
      is_important: 0,
      created_at: "2026-07-09 10:50:00",
    },
    {
      id: 3,
      title: "Hostel cultural night",
      content: "Registrations are open for music, dance, and stand-up performances.",
      category: "Events",
      is_important: 0,
      created_at: "2026-07-09 10:50:00",
    },
  ],
  messMenu: [
    {
      id: 1,
      day_of_week: "Monday",
      meal_type: "Breakfast",
      menu_items: "Poha, banana, tea",
      created_at: "2026-07-09 10:50:00",
    },
    {
      id: 2,
      day_of_week: "Monday",
      meal_type: "Lunch",
      menu_items: "Rice, dal tadka, paneer masala, salad",
      created_at: "2026-07-09 10:50:00",
    },
    {
      id: 3,
      day_of_week: "Tuesday",
      meal_type: "Dinner",
      menu_items: "Chapati, rajma, jeera rice, gulab jamun",
      created_at: "2026-07-09 10:50:00",
    },
    {
      id: 4,
      day_of_week: "Wednesday",
      meal_type: "Breakfast",
      menu_items: "Idli, sambar, coconut chutney",
      created_at: "2026-07-09 10:50:00",
    },
  ],
  lostFound: [
    {
      id: 1,
      student_id: 1,
      item_name: "Calculator",
      description: "Black scientific calculator with initials S.M.",
      location: "Reading room",
      status: "Lost",
      contact_info: "9876543210",
      created_at: "2026-07-09 10:50:00",
      full_name: "Satyam Mall",
    },
    {
      id: 2,
      student_id: 2,
      item_name: "Water bottle",
      description: "Blue steel bottle found near hostel gate.",
      location: "Main gate",
      status: "Found",
      contact_info: "aarav@hostelhub.com",
      created_at: "2026-07-09 10:50:00",
      full_name: "Aarav Singh",
    },
  ],
};
